### PR TITLE
Give the backend selection proccess a deterministic behavior.

### PR DESCRIPTION
**Pull request by henninge**
This is a fix for #35. I saw that you already had an incomplete branch that addressed the same problem by ordering the backends. Maybe this simpler approach works for you?

I guess the order is up for debate but at least this gives the whole process some predictability.

### CODE REVIEW

**Comment by cv** [comment]
Thanks @henninge! I had the same issue and tested your change, and it works perfectly.

**Comment by christophgysin** [comment]
I also ran into this issue. Can we  get this merged please?

**Comment by lox** [comment]
Apologies for the delay, I was considering whether we should update the whole approach of init() registering the drivers, but I reckon this is a pragmatic solution in the meantime. Thanks for your work @henninge and sorry it's taken so long. 🙇🏼‍♂️

**Comment by henninge** [comment]
Cool, thank you! I can totally understand the consideration for a different approach.

**Pull request merged**
