### PR TITLE
Add a password-store (aka pass) backend

### PR DESCRIPTION
**Pull request by dgoodlad**
This is a work-in-progress, naive implementation that just shells out to ["the standard unix password manager"](https://www.passwordstore.org/), `pass`, for most uses.

The `testdata/gnupghome` directory contains the result of

```
unset GPG_AGENT_INFO
unset GPG_TTY
mkdir testdata/gnupghome
export GNUPGHOME=$(pwd)/testdata/gnupghome
gpg --passphrase '' --quick-generate-key test@example.com \
  default default never
```

@lox this is what we were rambling about on Twitter, just wanted to get a feel for whether this is a direction worth going. I've not even tested it in aws-vault yet :joy:

---

obviously this won't pass CI, since we'd need `pass` and `gpg` installed there.

### CODE REVIEW

**Comment by dgoodlad** [comment]
I had a quick go (or 6) at getting this building in CI; it's fine in the linux build but not in macos because of restrictions writing to system directories. If this ends up being something the maintainers want to proceed with, I'll then put the effort into fighting that battle.

**Comment by lox** [comment]
Finally getting around to reviewing this! Btw, there is some prior art over at https://github.com/docker/docker-credential-helpers/blob/master/pass/pass_linux.go.

**Comment by lox** [comment]
Any idea what the CI failures might be @dgoodlad? Perhaps pass is prompting for something?

**Comment by lsowen** [comment]
@dgoodlad maybe install pass through brew as well on OSX?

**Comment by dimamedvedev** [comment]
Just wanted to say thank you for the PR, folks, and is there anything I can do to help it get merged?

**Comment by rekahsoft** [comment]
What's the status on this?

**Comment by keymon** [comment]
I am also interested on this. What is the status? @dgoodlad and @lox?

**Comment by rekahsoft** [comment]
@lox @keymon I have resolved the ci failure for osx in #33 (based of @dgoodlad's work).

**Pull request merged**
